### ISSUE TITLE
Incomplete installation doc?

### ISSUE THREAD

**Issue by pyros2097** [isage/lua-resty-moongoo#2]
How do I install this for my openresty stack and does this support all features of latest mongodb 3.4??

**Comment by isage** [comment]
1) Same as with any other pre-opm lua-resty-* - install requirements and put it in your openresty lua lib path. There's no plan to support opm until it supports C modules (because lua-libbson is a C module)
2) No. For example there's no support for CA or client certificates, as it states in the docs.
