### ISSUE TITLE
Saving nil values

### ISSUE THREAD

**Issue by travisbell** [isage/lua-resty-moongoo#5]
Hey man, I've continued to work on the stuff I mentioned in my previous issue and Moongoo has been working really well. Thanks for all the work here.

I have the need to store nil values. I can see in the docs you made the deliberate decision to ignore them for now. What would I need to change/update to store nil values? I took a look around and I *think* this is something that would have to change with your lua-cbson library, is that right?

**Comment by isage** [comment]
yep. as far as i remember, lua just doesn't pass nil to C code, so you'll
need custom cbson:nil in lua-cbson.

**Comment by isage** [comment]
You need "Null" bson datatype, right?
Do you have any example data available?
btw, lua-cbson currently decodes bson Null as lua nil, but does not encode them back.
I've done some experimenting, and when restoring Null fields as lua nil, lua loses those fields  (well, because nil in lua effectively unsets field)
So we should store and restore those fields as cbson:null. 
If that's what you want, i have this feature ready to commit.

**Comment by travisbell** [comment]
> So we should store and restore those fields as cbson:null.

Yes, that's exactly it. Basically in my case I was just saving an object field and then going to and from JSON with it. But when I tried saving the data, my 2 nil fields disappear. I get why it's happening, I was hoping there's a way to save the nil data, so a way to encode and decode that value is exactly what I need.

If you have a way to encode and decode cbson:null then I'd think that's all I need.

**Comment by isage** [comment]
Should work with latest lua-cbson
```lua
local t = bson.decode(bson.encode({c=bson.int(100500),a=bson.null()}))
print(t['a'] == bson:null())
```

**Comment by travisbell** [comment]
Works like a charm, thanks @isage!
